export const products = [
  {
    id: 1,
    name: "Thunderobot BF6_1077",
    description: "Мощный игровой ПК с Intel Core Ultra 7 и RTX 5090 для ультра-настроек в любых играх.",
    price: 149999,
    discountedPrice: 134999,
    images: ["assets/images/products/computer1.png"],
    specs: [
      { key: "Производитель", value: "Thunderobot" },
      { key: "Тип процессора", value: "Core Ultra 7" },
      { key: "Процессор", value: "Intel Core Ultra 7 165H" },
      { key: "Видеокарта", value: "RTX 5090" },
      { key: "Объём видеопамяти", value: "32 ГБ GDDR7" },
      { key: "Оперативная память", value: "64 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "2 ТБ NVMe" },
      { key: "Мощность блока питания", value: "1000 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 7, Bluetooth 5.4" },
    ],
  },
  {
    id: 2,
    name: "MSI Vortex G65",
    description: "Компактный геймерский десктоп с AMD Ryzen 9 и RTX 5080, идеален для стриминга.",
    price: 129999,
    discountedPrice: 116999,
    images: ["assets/images/products/computer2.png"],
    specs: [
      { key: "Производитель", value: "MSI" },
      { key: "Тип процессора", value: "Ryzen 9" },
      { key: "Процессор", value: "AMD Ryzen 9 9950X" },
      { key: "Видеокарта", value: "RTX 5080" },
      { key: "Объём видеопамяти", value: "24 ГБ GDDR7" },
      { key: "Оперативная память", value: "32 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "1 ТБ NVMe" },
      { key: "Мощность блока питания", value: "850 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 6E, Bluetooth 5.3" },
    ],
  },
  {
    id: 3,
    name: "Alienware Aurora R16",
    description: "Премиум ПК от Dell с Intel Core i9 и RTX 5090, с RGB-подсветкой и жидкостным охлаждением.",
    price: 169999,
    discountedPrice: null,
    images: ["assets/images/products/computer3.png"],
    specs: [
      { key: "Производитель", value: "Dell Alienware" },
      { key: "Тип процессора", value: "Core i9" },
      { key: "Процессор", value: "Intel Core i9-15900K" },
      { key: "Видеокарта", value: "RTX 5090" },
      { key: "Объём видеопамяти", value: "32 ГБ GDDR7" },
      { key: "Оперативная память", value: "64 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "2 ТБ NVMe" },
      { key: "Мощность блока питания", value: "1000 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 7, Bluetooth 5.4" },
    ],
  },
  {
    id: 4,
    name: "ASUS ROG Strix G16",
    description: "Баланс цены и производительности с Intel Core i7 и RTX 4070 Ti для 1440p гейминга.",
    price: 109999,
    discountedPrice: 98999,
    images: ["assets/images/products/computer4.png"],
    specs: [
      { key: "Производитель", value: "ASUS" },
      { key: "Тип процессора", value: "Core i7" },
      { key: "Процессор", value: "Intel Core i7-15700K" },
      { key: "Видеокарта", value: "RTX 4070 Ti" },
      { key: "Объём видеопамяти", value: "16 ГБ GDDR6X" },
      { key: "Оперативная память", value: "32 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "1 ТБ NVMe" },
      { key: "Мощность блока питания", value: "750 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 6E, Bluetooth 5.3" },
    ],
  },
  {
    id: 5,
    name: "HP Omen 45L",
    description: "Модульный ПК с AMD Ryzen 7 и RTX 4080, легко апгрейдить компоненты.",
    price: 139999,
    discountedPrice: 125999,
    images: ["assets/images/products/computer5.png"],
    specs: [
      { key: "Производитель", value: "HP" },
      { key: "Тип процессора", value: "Ryzen 7" },
      { key: "Процессор", value: "AMD Ryzen 7 9850X3D" },
      { key: "Видеокарта", value: "RTX 4080" },
      { key: "Объём видеопамяти", value: "16 ГБ GDDR6X" },
      { key: "Оперативная память", value: "64 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "2 ТБ NVMe" },
      { key: "Мощность блока питания", value: "1000 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 7, Bluetooth 5.4" },
    ],
  },
  {
    id: 6,
    name: "Corsair One i500",
    description: "Компактный high-end ПК с Intel Core i9 и RTX 5090 в стильном корпусе.",
    price: 189999,
    discountedPrice: null,
    images: ["assets/images/products/computer6.png"],
    specs: [
      { key: "Производитель", value: "Corsair" },
      { key: "Тип процессора", value: "Core i9" },
      { key: "Процессор", value: "Intel Core i9-15900KS" },
      { key: "Видеокарта", value: "RTX 5090" },
      { key: "Объём видеопамяти", value: "32 ГБ GDDR7" },
      { key: "Оперативная память", value: "64 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "4 ТБ NVMe" },
      { key: "Мощность блока питания", value: "1000 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 6E, Bluetooth 5.3" },
    ],
  },
  {
    id: 7,
    name: "Lenovo Legion Tower 7i",
    description: "Доступный геймерский ПК с Intel Core i5 и RTX 5070 для начинающих энтузиастов.",
    price: 99999,
    discountedPrice: 89999,
    images: ["assets/images/products/computer7.png"],
    specs: [
      { key: "Производитель", value: "Lenovo" },
      { key: "Тип процессора", value: "Core i5" },
      { key: "Процессор", value: "Intel Core i5-15500" },
      { key: "Видеокарта", value: "RTX 5070" },
      { key: "Объём видеопамяти", value: "12 ГБ GDDR7" },
      { key: "Оперативная память", value: "32 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "1 ТБ NVMe" },
      { key: "Мощность блока питания", value: "850 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 7, Bluetooth 5.4" },
    ],
  },
  {
    id: 8,
    name: "Acer Predator Orion 7000",
    description: "Агрессивный дизайн с AMD Ryzen 5 и RTX 4080, для фанатов киберспорта.",
    price: 119999,
    discountedPrice: 107999,
    images: ["assets/images/products/computer8.png"],
    specs: [
      { key: "Производитель", value: "Acer" },
      { key: "Тип процессора", value: "Ryzen 5" },
      { key: "Процессор", value: "AMD Ryzen 5 9600X" },
      { key: "Видеокарта", value: "RTX 4080" },
      { key: "Объём видеопамяти", value: "16 ГБ GDDR6X" },
      { key: "Оперативная память", value: "32 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "2 ТБ NVMe" },
      { key: "Мощность блока питания", value: "1000 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 6E, Bluetooth 5.3" },
    ],
  },
  {
    id: 9,
    name: "Gigabyte Aorus Model H5",
    description: "Профессиональный ПК с Intel Core i7 и RTX 5090 для контент-креаторов.",
    price: 159999,
    discountedPrice: 143999,
    images: ["assets/images/products/computer9.png"],
    specs: [
      { key: "Производитель", value: "Gigabyte" },
      { key: "Тип процессора", value: "Core i7" },
      { key: "Процессор", value: "Intel Core i7-15700" },
      { key: "Видеокарта", value: "RTX 5090" },
      { key: "Объём видеопамяти", value: "32 ГБ GDDR7" },
      { key: "Оперативная память", value: "64 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "2 ТБ NVMe" },
      { key: "Мощность блока питания", value: "1000 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 7, Bluetooth 5.4" },
    ],
  },
  {
    id: 10,
    name: "CyberPowerPC Gamer Supreme",
    description: "Кастомный сбор с AMD Ryzen 9 и RTX 5080, оптимизирован для VR.",
    price: 179999,
    discountedPrice: null,
    images: ["assets/images/products/computer10.png"],
    specs: [
      { key: "Производитель", value: "CyberPowerPC" },
      { key: "Тип процессора", value: "Ryzen 9" },
      { key: "Процессор", value: "AMD Ryzen 9 9950X" },
      { key: "Видеокарта", value: "RTX 5080" },
      { key: "Объём видеопамяти", value: "24 ГБ GDDR7" },
      { key: "Оперативная память", value: "64 ГБ" },
      { key: "Тип памяти", value: "DDR5" },
      { key: "Объём SSD", value: "4 ТБ NVMe" },
      { key: "Мощность блока питания", value: "1000 Вт" },
      { key: "Беспроводной интерфейс", value: "Wi-Fi 6E, Bluetooth 5.3" },
    ],
  },
];
